#!/usr/bin/env python3
"""build_action_library.py — Génère action_library_raw.json (étapes 2+3)."""
import json, time
from pathlib import Path

OUT = Path(__file__).parent / "data" / "action_library_raw.json"
OUT.parent.mkdir(parents=True, exist_ok=True)

actions = [
# ─────────────────────────────────────────────── KPI Y — Engagement + EAE
{
  "action_id": "ACT_001",
  "titre": "Flash Training métier",
  "description_technique": "Sessions courtes (format déjeuner) animées par des collaborateurs CACEIS pour présenter des sujets métiers, projets ou réglementations à leurs pairs. Dispositif récurrent documenté dans le Bilan Social 2023 comme outil d'engagement et de diffusion des connaissances internes.",
  "description_metier": "Des collègues partagent leur expertise en 30 min sur l'heure du déjeuner. Ça crée du lien entre équipes et aide chacun à comprendre comment son travail s'inscrit dans le métier CACEIS.",
  "gap_trigger": "Y < 3.40",
  "pattern_trigger": None,
  "kpi_cible": "Y",
  "career_development": False,
  "type": "Formation interne",
  "programme_parent": "FAB'Life",
  "duree": "1 heure",
  "organisme": "CACEIS (animé par pairs)",
  "profil_cible": "Tous collaborateurs",
  "impact_attendu_technique": "Amélioration du sentiment de contribution (item IMR : 'mon travail contribue à la satisfaction de mes clients internes/externes', score 89 en 2023)",
  "impact_attendu_metier": "Les équipes comprennent mieux le travail des autres — réduit les silos et renforce la fierté d'appartenance.",
  "delai_effet": "3-6 mois",
  "source_evidence": ["Bilan Social 2023 VF.pdf"],
  "extrait_source": "Flash Training : des présentations liées aux métiers, projets, réglementations faites par les collaborateurs à destination de leurs collègues à l'heure du déjeuner.",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_002",
  "titre": "Team Lunch annuel",
  "description_technique": "Déjeuner d'équipe annuel organisé et financé par CACEIS, permettant les échanges informels entre collaborateurs d'une même équipe. Documenté dans le Bilan Social 2023 comme action de cohésion sociale et d'engagement.",
  "description_metier": "Un repas d'équipe payé par CACEIS, une fois par an. Simple mais efficace pour maintenir la cohésion — surtout dans un contexte de télétravail étendu (84 jours/an).",
  "gap_trigger": "Y < 3.40",
  "pattern_trigger": None,
  "kpi_cible": "Y",
  "career_development": False,
  "type": "Initiative QVCT",
  "programme_parent": "FAB'Life",
  "duree": "Demi-journée, annuel",
  "organisme": "CACEIS",
  "profil_cible": "Toutes les équipes",
  "impact_attendu_technique": "Non quantifié dans les sources",
  "impact_attendu_metier": "Renforce la convivialité et le sentiment d'appartenance à l'équipe.",
  "delai_effet": "1-3 mois",
  "source_evidence": ["Bilan Social 2023 VF.pdf"],
  "extrait_source": "TeamLunch : déjeuner d'équipe annuel permettant l'échange informel et la convivialité.",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_003",
  "titre": "Outils feedback et développement",
  "description_technique": "Deux outils digitaux complémentaires déployés groupe : (1) Application FEEDBACK (demande de feedback asynchrone entre pairs, documentée dans l'Accord QVT 2024) ; (2) Application COSS PRO, outil de développement personnel déployé dans 11 entités du Groupe (Bilan Social 2023).",
  "description_metier": "Deux applis pour progresser : une pour demander un retour à ses collègues quand on veut, une autre pour travailler sur son développement personnel. Disponibles dans 11 entités du groupe.",
  "gap_trigger": "Y < 3.40",
  "pattern_trigger": None,
  "kpi_cible": "Y",
  "career_development": False,
  "type": "Dispositif RH",
  "programme_parent": "Accord QVT",
  "duree": "Usage continu",
  "organisme": "CACEIS (déploiement groupe)",
  "profil_cible": "Tous collaborateurs",
  "impact_attendu_technique": "Renforce la culture du feedback, levier de la dimension 'Mon manager / développement' dans l'IMR (score manager 84 en 2023)",
  "impact_attendu_metier": "Permet de donner et recevoir des retours sans attendre l'entretien annuel — utile pour progresser rapidement.",
  "delai_effet": "6 mois",
  "source_evidence": ["Bilan Social 2023 VF.pdf", "Suivi accord mixité diversité QVT 2024 vDef.pdf"],
  "extrait_source": "Application FEEDBACK permettant de demander du feedback. Utilisation de l'application de développement personnel COSS PRO dans 11 entités du Groupe.",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_004",
  "titre": "Meet Your Executive",
  "description_technique": "Sessions de dialogue direct entre groupes de collaborateurs et membres de la direction CACEIS. 10 sessions organisées en 2023. Dispositif de communication ascendante permettant aux collaborateurs de poser des questions stratégiques directement aux dirigeants. Documenté dans l'Accord QVT 2024.",
  "description_metier": "Des réunions en petit groupe avec la direction — pour poser ses questions directement et comprendre les orientations stratégiques. 10 sessions ont eu lieu en 2023.",
  "gap_trigger": "Y < 3.40",
  "pattern_trigger": None,
  "kpi_cible": "Y",
  "career_development": False,
  "type": "Dispositif RH",
  "programme_parent": "Accord QVT",
  "duree": "1-2 heures par session",
  "organisme": "CACEIS",
  "profil_cible": "Tous collaborateurs (sélection par session)",
  "impact_attendu_technique": "Agit sur les items IMR 'confiance dans les décisions des dirigeants' (IER 2021 : 63%) et 'je comprends la stratégie de mon entreprise' (IMR2022 : 67%)",
  "impact_attendu_metier": "Les collaborateurs comprennent mieux les décisions de l'entreprise — réduit l'incertitude et le sentiment de ne pas être informé.",
  "delai_effet": "3-6 mois",
  "source_evidence": ["Suivi accord mixité diversité QVT 2024 vDef.pdf"],
  "extrait_source": "10 Meet your executive organisés en 2023. Dispositif d'incitation des managers à organiser annuellement une réunion d'équipe portant sur les thèmes liés à la qualité de vie et au bien-être au travail.",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_005",
  "titre": "Communication managériale structurée",
  "description_technique": "Deux dispositifs de communication descendante : (1) Manager's Letter — newsletter mensuelle (France, Luxembourg) et trimestrielle (Groupe), présentant 3 sujets d'actualité RH (EAE, recueil besoins formation…) ; (2) Rendez-vous du Management — réunion toutes les 6 semaines, 2h, couvrant un sujet client + actualités RH pour tous les managers.",
  "description_metier": "Les managers reçoivent chaque mois une newsletter sur les sujets RH du moment, et se réunissent toutes les 6 semaines pour partager. Ça leur donne les clés pour animer leurs équipes au fil de l'eau.",
  "gap_trigger": "Y < 3.40",
  "pattern_trigger": None,
  "kpi_cible": "Y",
  "career_development": False,
  "type": "Dispositif RH",
  "programme_parent": None,
  "duree": "Mensuel (lettre) / toutes les 6 semaines (réunion)",
  "organisme": "CACEIS RH",
  "profil_cible": "Managers",
  "impact_attendu_technique": "Levier sur la dimension 'Mon manager' de l'IMR (score 84 en 2023) — améliore la posture et l'accessibilité managériale",
  "impact_attendu_metier": "Un manager mieux informé = une équipe mieux animée. Ces dispositifs réduisent les angles morts managériaux.",
  "delai_effet": "3-6 mois",
  "source_evidence": ["Bilan Social 2023 VF.pdf"],
  "extrait_source": "Manager's Letter : newsletter mensuelle pour présenter 3 sujets d'actualité aux managers. Les Rendez-vous du Management (toutes les 6 semaines environ) : 2 heures pour tous les managers.",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_006",
  "titre": "Baromètre IMR engagement annuel",
  "description_technique": "Enquête d'engagement annuelle (prestataire Ipsos Engage) déployée sur l'ensemble du groupe CACEIS. Mesure : IMR Accountability Index, qualité managériale, conditions de travail, QVCT. Historique disponible : IER 2021, IMR 2022, 2023, 2024. Déclenchée chaque automne (ex: 12 sept–3 oct 2023).",
  "description_metier": "Une enquête annuelle pour mesurer comment les collaborateurs vivent leur travail — les résultats déclenchent les actions RH ciblées par BU.",
  "gap_trigger": "Cycle annuel — déclenchement si Y < 3.40 ou score IMR BU < score groupe",
  "pattern_trigger": None,
  "kpi_cible": "Y",
  "career_development": False,
  "type": "Dispositif RH",
  "programme_parent": None,
  "duree": "3 semaines terrain, annuel",
  "organisme": "Ipsos Engage (prestataire)",
  "profil_cible": "Tous collaborateurs",
  "impact_attendu_technique": "Outil de pilotage permettant d'identifier les BU sous-performantes. IMR 2023 groupe : score 76 (Accountability Index). IMR 2024 disponible.",
  "impact_attendu_metier": "Mesurer pour agir : sans données, impossible de cibler les équipes qui ont vraiment besoin d'aide.",
  "delai_effet": "12 mois (cycle annuel)",
  "source_evidence": ["Suivi accord mixité diversité QVT 2024 vDef.pdf", "IMR2023_CACEIS_GROUP.pdf"],
  "extrait_source": "L'IMR du 12 septembre au 3 octobre 2023. Dispositif d'incitation des managers à organiser annuellement une réunion d'équipe portant sur les thèmes liés à la QVT et au bien-être au travail.",
  "a_completer": False,
  "note_extraction": "IMR 2023/2024 : chunks OCR (tableaux de scores). Contenu actionnable limité — utiliser comme contexte de score, pas comme source d'actions."
},
{
  "action_id": "ACT_007",
  "titre": "Entretien annuel EAE",
  "description_technique": "EAE structuré annuel (avec révision à mi-année) couvrant : description de poste, évaluation des compétences, atteinte des objectifs, fixation des objectifs N+1, commentaires et signatures. Taux de réalisation 2021 : 94% (IER). Piloté par les managers, suivi par les HRBP.",
  "description_metier": "L'entretien annuel permet à chaque collaborateur de faire le point sur ses résultats et ses objectifs pour l'année suivante. Obligatoire pour tous les CDI — 94% l'ont eu en 2021.",
  "gap_trigger": "Taux EAE réalisés < 90% OU Y < 3.40",
  "pattern_trigger": None,
  "kpi_cible": "Y",
  "career_development": False,
  "type": "Dispositif RH",
  "programme_parent": None,
  "duree": "1-2 heures, annuel",
  "organisme": "CACEIS (managers + HRBP)",
  "profil_cible": "Tous collaborateurs CDI",
  "impact_attendu_technique": "IER 2021 : 94% ont eu un EAE (vs 73% groupe CASA). Score 'gestion de la performance' : 70 (IER 2021).",
  "impact_attendu_metier": "Quand l'entretien est bien mené, les collaborateurs comprennent ce qu'on attend d'eux — réduit le flou et améliore la motivation.",
  "delai_effet": "6-12 mois",
  "source_evidence": ["Bilan Social 2023 VF.pdf", "IER 2021.pdf"],
  "extrait_source": "Les entretiens annuels d'évaluation ont lieu 1 fois par an avec une campagne de révision des objectifs à mi-année. Chaque collaborateur en CDI est évalué par son manager.",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_008",
  "titre": "Entretien professionnel carrière",
  "description_technique": "Entretien professionnel annuel distinct de l'EAE, mené par le manager : souhaits de mobilité, plan de développement des compétences, équilibre vie pro/perso (obligatoire cadres au forfait). Complété par entretiens de gestion de carrière à l'initiative HRBP ou du collaborateur.",
  "description_metier": "Un entretien spécifique centré sur la trajectoire professionnelle : où veut-on aller, quelles compétences développer, quelle mobilité envisager. Le HRBP peut aussi le déclencher à tout moment.",
  "gap_trigger": "Y < 3.40 ET score 'développement de carrière' IMR bas",
  "pattern_trigger": None,
  "kpi_cible": "Y",
  "career_development": False,
  "type": "Dispositif RH",
  "programme_parent": None,
  "duree": "1 heure, annuel",
  "organisme": "CACEIS (managers + HRBP)",
  "profil_cible": "Tous collaborateurs (cadres au forfait : obligatoire)",
  "impact_attendu_technique": "Levier direct sur 'développement de carrière' (IER 2021 : 55) et 'rétention' (46) — deux des scores les plus bas dans l'IER 2021.",
  "impact_attendu_metier": "Montre à chaque collaborateur qu'il a un avenir chez CACEIS — levier de fidélisation important sur les profils qualifiés.",
  "delai_effet": "6-12 mois",
  "source_evidence": ["Bilan Social 2023 VF.pdf"],
  "extrait_source": "Les entretiens professionnels sont menés par le manager une fois par an. Les entretiens de gestion de carrière se font à l'initiative des HRBP ou bien à la demande des collaborateurs.",
  "a_completer": False,
  "note_extraction": None
},
# ─────────────────────────────────────────────── KPI λ — Formation
{
  "action_id": "ACT_009",
  "titre": "Plan développement des compétences",
  "description_technique": "Engagement Accord QVT 2022-2025 : ≥90% des collaborateurs formés chaque année (hors formations obligatoires). Réalisation 2024 : 107% de l'effectif moyen mensuel (Cadres 71%, Non-cadres 29%). Budget formation France 2023 : 6 970 388€ (dont 3 361 956€ formation interne).",
  "description_metier": "CACEIS forme plus de collaborateurs que son effectif chaque année. Le plan couvre tout le monde — métiers, management, digital, langues — avec un budget en hausse continue.",
  "gap_trigger": "Taux réalisation plan formation < 90%",
  "pattern_trigger": None,
  "kpi_cible": "λ",
  "career_development": False,
  "type": "Formation interne",
  "programme_parent": "Accord QVT",
  "duree": "Programme annuel",
  "organisme": "CACEIS / IFCAM / prestataires externes",
  "profil_cible": "Tous collaborateurs",
  "impact_attendu_technique": "Objectif Accord : ≥90% formés. Réalisation 2024 : 107%. Bilan Social 2023 : 50 310 heures de formation (+37% vs 2022).",
  "impact_attendu_metier": "Un collaborateur qui se forme reste performant et se sent soutenu dans son évolution — levier direct sur l'engagement.",
  "delai_effet": "6-12 mois",
  "source_evidence": ["Suivi accord mixité diversité QVT 2024 vDef.pdf", "Bilan Social 2023 VF.pdf"],
  "extrait_source": "Au moins 90% des salariés bénéficient d'une formation dans les quatre années de l'accord en dehors des formations obligatoires. % formé de l'effectif moyen mensuel : 107% en 2024.",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_010",
  "titre": "Formation acculturation à l'IA",
  "description_technique": "Module obligatoire (0,5 jour) dispensé par Crédit Agricole SA, déployé sur CACEIS Bank à partir de janvier 2025. Statut : Réalisé. Référence planning : 2025-01-01. Source : Training Records CACEIS.",
  "description_metier": "Une demi-journée pour comprendre les bases de l'IA et ce qu'elle change pour les métiers de CACEIS. Dispensé par le Groupe Crédit Agricole.",
  "gap_trigger": "λ : acculturation digitale non réalisée",
  "pattern_trigger": None,
  "kpi_cible": "λ",
  "career_development": False,
  "type": "Formation externe",
  "programme_parent": None,
  "duree": "0,5 jour",
  "organisme": "Crédit Agricole SA",
  "profil_cible": "Collaborateurs CACEIS Bank",
  "impact_attendu_technique": "Non quantifié dans les sources",
  "impact_attendu_metier": "Prépare les équipes aux évolutions digitales du métier — réduit la résistance au changement liée aux outils IA.",
  "delai_effet": "3-6 mois",
  "source_evidence": ["Training_Records_Unnamed.xlsx"],
  "extrait_source": "Formation Acculturation l'IA | Crédit Agricole SA | 2025-01-01 | Réalisé | 0.5 jour",
  "a_completer": False,
  "note_extraction": "Source XLSX — un enregistrement disponible, représentatif d'un déploiement en cours sur CACEIS Bank."
},
{
  "action_id": "ACT_011",
  "titre": "Formation biais inconscients",
  "description_technique": "Module obligatoire d'une journée sur les biais inconscients, dispensé par Me and You Too, déployé sur CACEIS Bank à partir de janvier 2025. Statut : Réalisé. Référence planning : 2025-01-04.",
  "description_metier": "Formation d'une journée pour identifier ses propres biais dans les décisions RH (recrutement, évaluation, promotion). Obligatoire — dispensé par un prestataire externe spécialisé.",
  "gap_trigger": "Score D&I inclusion < 70% OU formation biais non réalisée",
  "pattern_trigger": None,
  "kpi_cible": "λ",
  "career_development": False,
  "type": "Formation externe",
  "programme_parent": None,
  "duree": "1 jour",
  "organisme": "Me and You Too",
  "profil_cible": "Managers + RH (CACEIS Bank)",
  "impact_attendu_technique": "Non quantifié dans les sources",
  "impact_attendu_metier": "Aide les managers à évaluer leurs équipes plus équitablement — levier de confiance et d'équité perçue.",
  "delai_effet": "6 mois",
  "source_evidence": ["Training_Records_Unnamed.xlsx"],
  "extrait_source": "Formation obligatoire - Biais inconscients | Me and You Too | 2025-01-04 | Réalisé | 1 jour",
  "a_completer": False,
  "note_extraction": "Source XLSX — un enregistrement. Formation obligatoire en déploiement sur CACEIS Bank."
},
{
  "action_id": "ACT_012",
  "titre": "E-learning et blended learning",
  "description_technique": "Modalité pédagogique inscrite dans l'Accord QVT 2022-2025 : favoriser l'e-learning pur ou blended learning (présentiel + digital). Contraintes définies : formations hors mercredi, sessions courtes, au plus près du lieu de travail, accès facilité pour les publics sous-représentés.",
  "description_metier": "CACEIS adapte ses formations en proposant des formats mixtes (distanciel + présentiel) et des modules courts — pour que chacun puisse se former sans bloquer des semaines entières.",
  "gap_trigger": "λ < 80% OU taux complétion formations < seuil accord",
  "pattern_trigger": None,
  "kpi_cible": "λ",
  "career_development": False,
  "type": "Formation interne",
  "programme_parent": "Accord QVT",
  "duree": "Variable — modules courts",
  "organisme": "CACEIS",
  "profil_cible": "Tous collaborateurs",
  "impact_attendu_technique": "Hausse heures formation : Bilan Social 2023 France : 50 310h (+37% vs 36 668h en 2022). Corrélation avec déploiement blended.",
  "impact_attendu_metier": "Des formats souples qui s'intègrent dans l'agenda sans contrainte — augmente le taux de complétion des formations.",
  "delai_effet": "3-6 mois",
  "source_evidence": ["Suivi accord mixité diversité QVT 2023 VF.pdf"],
  "extrait_source": "Un point de vigilance particulier sera porté à l'optimisation de la durée des formations, et la possibilité d'effectuer ces formations en e-learning ou en blended learning (apports en e-learning et présentiel).",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_013",
  "titre": "Formation de formateurs internes",
  "description_technique": "Parcours 3 modules LEFEBVRE DALLOZ : (1) Préparer ma formation, (2) Animer ma formation, (3) Développer les compétences par la posture de coach. Référencé Training Records 2024-2025 CACEIS Bank. Statut sessions 2024 : Annulée selon les données disponibles.",
  "description_metier": "Un parcours pour apprendre à former ses collègues — utile pour internaliser la transmission des compétences et réduire la dépendance aux formateurs externes.",
  "gap_trigger": "λ : capacité formateurs internes insuffisante",
  "pattern_trigger": None,
  "kpi_cible": "λ",
  "career_development": False,
  "type": "Formation externe",
  "programme_parent": None,
  "duree": "3 modules (durée unitaire non précisée dans les sources)",
  "organisme": "LEFEBVRE DALLOZ",
  "profil_cible": "Formateurs internes / référents métier",
  "impact_attendu_technique": "Non quantifié dans les sources",
  "impact_attendu_metier": "Des collaborateurs formés à former les autres accélèrent l'onboarding et développent l'expertise métier en interne.",
  "delai_effet": "6-12 mois",
  "source_evidence": ["Training_Records_Unnamed.xlsx"],
  "extrait_source": "Formation de formateurs - Module 1 : Préparer ma formation | Module 2 : Animer ma formation | Module 3 : posture du coach | LEFEBVRE DALLOZ | 2024-2025",
  "a_completer": True,
  "note_extraction": "Sessions 2024 avec statut 'Annulée' dans les Training Records. Vérifier statut réel du déploiement 2025."
},
# ─────────────────────────────────────────────── KPI β — QVCT / Bien-être
{
  "action_id": "ACT_014",
  "titre": "Accord télétravail 84 jours",
  "description_technique": "Accord télétravail UES CACEIS : 84 jours annualisés pour tous collaborateurs (CDI, CDD). Enveloppe équipement : 180€ pour l'achat de matériel informatique. Allocation forfaitaire : 2,60€/jour de télétravail (Avenant n°3). Confirmé dans Bilans Sociaux 2023 et 2024.",
  "description_metier": "CACEIS permet jusqu'à 84 jours de télétravail par an — avec une aide de 180€ pour l'équipement et 2,60€/jour de compensation forfaitaire. Disponible pour tout type de contrat.",
  "gap_trigger": "β < 3.40 OU score 'équilibre vie pro/perso' IMR < 70",
  "pattern_trigger": None,
  "kpi_cible": "β",
  "career_development": False,
  "type": "Dispositif RH",
  "programme_parent": "Accord QVT",
  "duree": "Permanent (accord en vigueur)",
  "organisme": "CACEIS (accord UES)",
  "profil_cible": "Tous collaborateurs CDI et CDD",
  "impact_attendu_technique": "IMR2023 : 'Mon entreprise me permet d'avoir un bon équilibre vie pro/perso' = 70 (favorable). IMR2022 : 66 (+4 pts).",
  "impact_attendu_metier": "Le télétravail avec une vraie aide matérielle améliore concrètement l'équilibre vie pro/perso — levier direct sur le bien-être quotidien.",
  "delai_effet": "1-3 mois",
  "source_evidence": ["Bilan Social 2023 VF.pdf", "Bilan Social 2024.pdf"],
  "extrait_source": "Accord Télétravail avec un quota de 84 jours annualisés pour tous les collaborateurs. Enveloppe dédiée de 180 euros. Allocation forfaitaire de 2,60 euros par jour de télétravail.",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_015",
  "titre": "Semaine QVT FAB'Life annuelle",
  "description_technique": "Semaine annuelle QVT depuis 2022 (France) et 2023 (groupe). Programme 2024 : webinaires sophrologie (Responsage), nutrition, concentration (Thibaud Dumas : 84 participants FR + 181 EN). Mois des Diversités, Mois de la Parentalité, Octobre Rose en complément.",
  "description_metier": "Une semaine de webinaires et événements sur le bien-être au travail — sophrologie, équilibre vie pro/perso, nutrition. Ouverte à tous, à distance ou en présentiel, à l'échelle du groupe.",
  "gap_trigger": "β < 3.40",
  "pattern_trigger": None,
  "kpi_cible": "β",
  "career_development": False,
  "type": "Initiative QVCT",
  "programme_parent": "FAB'Life",
  "duree": "1 semaine, annuel (juin)",
  "organisme": "CACEIS + Responsage + prestataires externes",
  "profil_cible": "Tous collaborateurs groupe CACEIS",
  "impact_attendu_technique": "Non quantifié dans les sources (participation 2024 : 84-181 participants par webinaire)",
  "impact_attendu_metier": "Crée un temps collectif autour du bien-être — visible, gratuit, accessible. Signal fort de l'engagement employeur.",
  "delai_effet": "3-6 mois",
  "source_evidence": ["Bilan FAB'Life 2024.pptx"],
  "extrait_source": "Depuis 2022, CACEIS organise la semaine de la QVT en France et depuis 2023 au niveau du groupe. Webinaire Booster sa Concentration : 84 participants (FR) + 181 participants (EN).",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_016",
  "titre": "Ligne Stimulus soutien psychologique",
  "description_technique": "Ligne d'écoute et d'accompagnement psychologique téléphonique (Stimulus Care Services), confidentielle. Budget dédié : 135 425€ en 2024 (vs 149 615€ en 2023). Complétée par assistante sociale et psychologue du travail sur site. Inclus dans le dispositif FAB'Life RPS.",
  "description_metier": "Un numéro confidentiel à appeler en cas de difficultés au travail ou personnelles — disponible 24h/24, géré par un prestataire externe. Compris dans le budget bien-être de CACEIS.",
  "gap_trigger": "β < 3.40 OU indicateur RPS élevé OU taux absentéisme maladie > 4%",
  "pattern_trigger": None,
  "kpi_cible": "β",
  "career_development": False,
  "type": "Initiative QVCT",
  "programme_parent": "FAB'Life",
  "duree": "Disponible en continu",
  "organisme": "Stimulus Care Services",
  "profil_cible": "Tous collaborateurs",
  "impact_attendu_technique": "Budget dédié 2024 : 135 425€. Levier direct sur la prévention des RPS et la réduction de l'absentéisme psychologique.",
  "impact_attendu_metier": "Un collaborateur en difficulté peut appeler sans que son manager le sache — ce filet de sécurité réduit les situations de burn-out non détectées.",
  "delai_effet": "1-3 mois (disponibilité immédiate)",
  "source_evidence": ["Bilan Social 2024.pdf", "Bilan Social 2023 VF.pdf"],
  "extrait_source": "Budget dédié à la promotion de la QVT et la prévention des RPS : 135 425€ sur 2024 (la ligne d'écoute et d'accompagnement psychologique Stimulus Care Services, l'assistante sociale, la psychologue du travail).",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_017",
  "titre": "Enquête RPS-QVT annuelle",
  "description_technique": "Enquête annuelle dédiée aux risques psychosociaux et à la qualité de vie au travail, distincte de l'IMR. Résultats alimentent le budget QVCT-RPS et les plans d'action. Mentionnée dans les Bilans Sociaux 2023 et 2024 comme composante du dispositif global FAB'Life.",
  "description_metier": "Une enquête interne pour mesurer le stress et les risques au travail — les résultats permettent de cibler les actions concrètes là où c'est le plus nécessaire.",
  "gap_trigger": "β < 3.40 OU signaux RPS détectés",
  "pattern_trigger": None,
  "kpi_cible": "β",
  "career_development": False,
  "type": "Dispositif RH",
  "programme_parent": "FAB'Life",
  "duree": "Annuel",
  "organisme": "CACEIS RH + psychologue du travail",
  "profil_cible": "Tous collaborateurs",
  "impact_attendu_technique": "Outil de diagnostic — non quantifié directement mais conditionne l'allocation du budget QVT-RPS (135 425€ en 2024)",
  "impact_attendu_metier": "Permet d'agir sur les bons leviers — sans mesurer, on ne peut pas améliorer ce qu'on ne voit pas.",
  "delai_effet": "6-12 mois (résultats → plan d'action)",
  "source_evidence": ["Bilan Social 2024.pdf", "Bilan Social 2023 VF.pdf"],
  "extrait_source": "Budget dédié à la promotion de la QVT : 135 425€ sur 2024 (l'enquête RPS-QVT, l'assistante sociale, la psychologue du travail, les actions de sensibilisation).",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_018",
  "titre": "Don de jours de repos",
  "description_technique": "Avenant n°2 sur le don de jours de repos : dispositif permettant aux collaborateurs CDI/CDD (ancienneté > 6 mois) de bénéficier de jours donnés par leurs collègues. Étendu aux travailleurs handicapés, proches aidants et collaborateurs avec trajet A/R > 3h. Documenté Bilan Social 2024.",
  "description_metier": "Des collègues peuvent donner leurs jours de congé à quelqu'un qui en a besoin — pour un proche malade, un aidant familial, ou une situation particulière. Disponible dès 6 mois d'ancienneté.",
  "gap_trigger": "β < 3.40 OU nombre de situations aidants identifiées élevé",
  "pattern_trigger": None,
  "kpi_cible": "β",
  "career_development": False,
  "type": "Dispositif RH",
  "programme_parent": "FAB'Life",
  "duree": "Continu (dispositif permanent)",
  "organisme": "CACEIS (accord UES)",
  "profil_cible": "Collaborateurs CDI/CDD > 6 mois (priorité : TH, proches aidants)",
  "impact_attendu_technique": "Non quantifié dans les sources",
  "impact_attendu_metier": "Montre que CACEIS est une entreprise humaine — renforce la solidarité entre collègues et réduit l'absentéisme non planifié.",
  "delai_effet": "1-3 mois",
  "source_evidence": ["Bilan Social 2024.pdf"],
  "extrait_source": "Avenant n°2 sur le don de jours de repos permettant aux collaborateurs en CDI/CDD ayant une ancienneté de plus de 6 mois de bénéficier de ces dons de jours (TH, proche aidant, trajet A/R supérieur à 3H).",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_019",
  "titre": "Conciergerie campus",
  "description_technique": "Service de conciergerie accessible sur le campus CACEIS (France), permettant aux collaborateurs de déléguer des démarches du quotidien. Documenté dans l'Accord QVT 2023 comme service contribuant à l'amélioration du bien-être des salariés.",
  "description_metier": "Un service sur site pour régler des petites tâches du quotidien (pressing, livraisons, démarches…) sans quitter le bureau — libère du temps et réduit le stress de la gestion personnelle.",
  "gap_trigger": "β < 3.40",
  "pattern_trigger": None,
  "kpi_cible": "β",
  "career_development": False,
  "type": "Initiative QVCT",
  "programme_parent": "FAB'Life",
  "duree": "Continu",
  "organisme": "CACEIS (service interne campus)",
  "profil_cible": "Collaborateurs sur site campus (France)",
  "impact_attendu_technique": "Non quantifié dans les sources",
  "impact_attendu_metier": "Petite amélioration concrète du quotidien — symbole d'un employeur attentif aux détails du quotidien.",
  "delai_effet": "Immédiat",
  "source_evidence": ["Suivi accord mixité diversité QVT 2023 VF.pdf"],
  "extrait_source": "Une Conciergerie sur le Campus est accessible afin de contribuer à l'amélioration du bien-être des salariés.",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_020",
  "titre": "Prise en charge mobilité douce",
  "description_technique": "Accord QVT 2022-2025 : prise en charge 90% de l'abonnement transports publics ou location de vélos (depuis janv. 2024). Actions complémentaires : parking vélos sécurisé, bornes recharge électriques, co-voiturage, auto-partage. Documenté Accords QVT 2023 et 2024.",
  "description_metier": "CACEIS rembourse 90% de votre abonnement de transports en commun depuis 2024 — et met en place des parkings vélos, bornes électriques et solutions de covoiturage sur le campus.",
  "gap_trigger": "β < 3.40 OU plaintes temps de trajet élevées",
  "pattern_trigger": None,
  "kpi_cible": "β",
  "career_development": False,
  "type": "Dispositif RH",
  "programme_parent": "Accord QVT",
  "duree": "Permanent (depuis janvier 2024)",
  "organisme": "CACEIS (accord UES)",
  "profil_cible": "Tous collaborateurs utilisant les transports en commun",
  "impact_attendu_technique": "Avantage économique direct (prise en charge 90%). Levier sur 'équilibre vie pro/perso' de l'IMR.",
  "impact_attendu_metier": "Réduit le coût et le stress du trajet quotidien — un avantage concret qui se voit sur la fiche de paie.",
  "delai_effet": "1-3 mois",
  "source_evidence": ["Suivi accord mixité diversité QVT 2023 VF.pdf", "Suivi accord mixité diversité QVT 2024 vDef.pdf"],
  "extrait_source": "Prise en charge de l'abonnement aux transports publics à hauteur de 90% à compter du 1er janvier 2024 pour une durée indéterminée. Parking sécurisé dédié au stationnement de vélos.",
  "a_completer": False,
  "note_extraction": None
},
# ─────────────────────────────────────────────── KPI ρ — Absentéisme + Turnover
{
  "action_id": "ACT_021",
  "titre": "Entretien retour longue durée",
  "description_technique": "Dispositif obligatoire Accord QVT 2022-2025 : chaque collaborateur en retour d'absence longue durée doit être invité à un entretien HRBP dans l'année. Objectif : 100%. Réalisation 2023 : 96% (42F/6H sur 48 concernés). Documenté dans l'Accord QVT 2023.",
  "description_metier": "Quand un collaborateur revient d'une longue absence, son RH le recontacte pour un entretien de réintégration. 96% des collaborateurs concernés ont été invités en 2023.",
  "gap_trigger": "Taux absentéisme longue durée > seuil OU ρ > 4.5%",
  "pattern_trigger": None,
  "kpi_cible": "ρ",
  "career_development": False,
  "type": "Dispositif RH",
  "programme_parent": "Accord QVT",
  "duree": "1 entretien au retour",
  "organisme": "CACEIS HRBP",
  "profil_cible": "Collaborateurs en retour d'absence longue durée",
  "impact_attendu_technique": "Taux d'invitation 2023 : 96%. Contribue à réduire les rechutes d'absence et les départs post-arrêt.",
  "impact_attendu_metier": "Un accueil structuré au retour d'absence réduit l'anxiété de la reprise et limite les nouvelles absences.",
  "delai_effet": "6-12 mois",
  "source_evidence": ["Suivi accord mixité diversité QVT 2023 VF.pdf"],
  "extrait_source": "100% des salariés revenant après une absence de longue durée doivent avoir été invités à un entretien par leur gestionnaire RH dans l'année. Reçus ou invités en 2023 : 96%.",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_022",
  "titre": "Garantie salariale congé maternité",
  "description_technique": "Garantie de maintien du salaire au retour d'un congé maternité, adoption ou congé parental (article 53-1 CCN banque, accord UES CACEIS du 15 juin 2006). Étendue aux congés maternité conventionnels (45j, 90j) et à la grossesse pathologique.",
  "description_metier": "Le salaire des collaboratrices revenant d'un congé maternité est garanti — pas de perte de revenus liée à l'absence. Levier de fidélisation des femmes qualifiées.",
  "gap_trigger": "Turnover féminin > 15% OU ρ élevé population féminine",
  "pattern_trigger": None,
  "kpi_cible": "ρ",
  "career_development": False,
  "type": "Dispositif RH",
  "programme_parent": "Accord QVT",
  "duree": "Permanent (convention collective)",
  "organisme": "CACEIS (accord UES)",
  "profil_cible": "Collaboratrices en congé maternité / adoption / parental",
  "impact_attendu_technique": "Non quantifié sur ρ dans les sources. Levier rétention femmes : viviers Talents 51% femmes (2023), COMEX 15,9% femmes.",
  "impact_attendu_metier": "Une collaboratrice qui sait que sa carrière et son salaire sont préservés pendant sa maternité est plus susceptible de rester après le congé.",
  "delai_effet": "12 mois",
  "source_evidence": ["Suivi accord mixité diversité QVT 2023 VF.pdf", "Suivi accord mixité diversité QVT 2024 vDef.pdf"],
  "extrait_source": "L'Entreprise applique la garantie salariale au retour d'un congé de maternité (y compris congé parental prévu à l'article 53-1 de la convention collective nationale de la banque).",
  "a_completer": True,
  "note_extraction": "Levier indirect sur ρ (rétention). Impact direct sur le taux de turnover non quantifié dans les sources disponibles."
},
{
  "action_id": "ACT_023",
  "titre": "Étude équité salariale interne",
  "description_technique": "Outils DRH de fin d'année fournis aux managers : (1) étude d'équité interne comparant salaires individuels au médian sectoriel, (2) enquête de rémunération externe, (3) recommandations talent management. Résultats 2024 : écarts F/H de -2,7% à +0,9% (hors HC), amélioration vs 2022 (-1,6%/+4,5%).",
  "description_metier": "Chaque fin d'année, les RH donnent aux managers des données concrètes pour ajuster les salaires équitablement — en comparant aux pratiques du marché et en corrigeant les écarts internes.",
  "gap_trigger": "Écarts salariaux F/H > 3% OU turnover lié à insatisfaction salariale",
  "pattern_trigger": None,
  "kpi_cible": "ρ",
  "career_development": False,
  "type": "Dispositif RH",
  "programme_parent": "Accord QVT",
  "duree": "Annuel (processus fin d'année)",
  "organisme": "Direction des Ressources Humaines CACEIS",
  "profil_cible": "Managers (utilisateurs des outils) + DRH",
  "impact_attendu_technique": "Réduction écarts F/H : de -1,6%/+4,5% (2022) à -2,7%/+0,9% (2024) — tendance positive sur 3 ans.",
  "impact_attendu_metier": "Des salaires plus équitables réduisent les départs liés à un sentiment d'injustice salariale — levier de rétention indirect mais mesurable.",
  "delai_effet": "12 mois",
  "source_evidence": ["Suivi accord mixité diversité QVT 2023 VF.pdf", "Suivi accord mixité diversité QVT 2024 vDef.pdf"],
  "extrait_source": "Outils d'aide à la décision fournis aux managers pendant les mesures de fin d'année : étude d'équité interne, enquête de rémunération externe, recommandations de la gestion individuelle et talent management.",
  "a_completer": True,
  "note_extraction": "Levier indirect sur ρ (rétention salariale). Impact sur le taux de turnover non isolé dans les sources disponibles."
},
# ─────────────────────────────── Career Development → kpi_cible Y, career_development true
{
  "action_id": "ACT_024",
  "titre": "Programme YoungTalents",
  "description_technique": "Programme d'accélération de carrière pour nouveaux talents CACEIS, en promotions annuelles. 7ème promotion lancée en octobre 2023. Closing 6ème promotion mai 2023. Objectif : complémentarité intergénérationnelle et accompagnement des profils à haut potentiel. Documenté Accords QVT 2023 et 2024.",
  "description_metier": "Un programme annuel pour les jeunes talents identifiés chez CACEIS — accélère leur montée en compétences et leur visibilité dans l'entreprise. La 7ème promotion a démarré en octobre 2023.",
  "gap_trigger": "Y < 3.40",
  "pattern_trigger": "Y < 3.40 ET λ >= moyenne groupe (engagement faible malgré volume de formation correct → trajectoire perçue insuffisante)",
  "kpi_cible": "Y",
  "career_development": True,
  "type": "Coaching",
  "programme_parent": "Accord QVT",
  "duree": "Programme annuel (plusieurs mois)",
  "organisme": "CACEIS Talent Management",
  "profil_cible": "Jeunes collaborateurs à potentiel identifiés",
  "impact_attendu_technique": "Levier sur 'développement de carrière' IER 2021 : 55 (score le plus bas) et 'rétention' : 46.",
  "impact_attendu_metier": "Les jeunes talents qui voient une trajectoire claire restent plus longtemps — réduit le risque de départ vers la concurrence.",
  "delai_effet": "6-12 mois",
  "source_evidence": ["Suivi accord mixité diversité QVT 2024 vDef.pdf", "Suivi accord mixité diversité QVT 2023 VF.pdf"],
  "extrait_source": "Des dispositifs permettant d'accompagner de nouveaux talents tels que le programme YoungTalents continueront d'être déployés. Kick-Off de la 7ème promotion YoungTalents en octobre 2023.",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_025",
  "titre": "Manager'School",
  "description_technique": "Programme de formation managériale interne : futurs managers formés par des collaborateurs expérimentés CACEIS. 2ème promotion clôturée en octobre 2023. Objectif : développer le vivier managérial interne et la complémentarité intergénérationnelle. Documenté Accords QVT 2023 et 2024.",
  "description_metier": "Des futurs managers formés par des managers expérimentés de CACEIS — pas une école externe, une vraie transmission interne de savoir-faire. La 2ème promotion s'est terminée en octobre 2023.",
  "gap_trigger": "Y < 3.40",
  "pattern_trigger": "Y < 3.40 ET λ >= moyenne groupe (engagement faible malgré formation correcte → accès à la trajectoire managériale insuffisant)",
  "kpi_cible": "Y",
  "career_development": True,
  "type": "Coaching",
  "programme_parent": "Accord QVT",
  "duree": "Plusieurs mois (durée programme non précisée dans les sources)",
  "organisme": "CACEIS Talent Management",
  "profil_cible": "Futurs managers identifiés",
  "impact_attendu_technique": "Levier sur 'développement de carrière' (IER 2021 : 55) et qualité managériale IMR (dimension 'Mon manager' : 84 en 2023).",
  "impact_attendu_metier": "Former ses futurs managers en interne réduit le turnover managérial et améliore la qualité du management de proximité.",
  "delai_effet": "12 mois",
  "source_evidence": ["Suivi accord mixité diversité QVT 2024 vDef.pdf", "Suivi accord mixité diversité QVT 2023 VF.pdf"],
  "extrait_source": "Des dispositifs tels que la Manager'School, destiné à former des futurs managers par des collaborateurs expérimentés. Closing de la 2e promotion Manager'School en octobre 2023.",
  "a_completer": False,
  "note_extraction": None
},
{
  "action_id": "ACT_026",
  "titre": "Programme RisingLeader",
  "description_technique": "Programme d'accompagnement de nouveaux talents vers des rôles de leadership, cité conjointement avec YoungTalents dans les Accords QVT 2023 et 2024. Structure, durée et critères de sélection non détaillés dans les sources disponibles.",
  "description_metier": "Un programme pour accompagner les profils à fort potentiel vers des rôles de leadership — complémentaire de YoungTalents, peu documenté dans les sources disponibles.",
  "gap_trigger": "Y < 3.40",
  "pattern_trigger": "Y < 3.40 ET λ >= moyenne groupe (trajectoire leadership non visible malgré bon volume formation)",
  "kpi_cible": "Y",
  "career_development": True,
  "type": "Coaching",
  "programme_parent": "Accord QVT",
  "duree": "Non précisé dans les sources",
  "organisme": "CACEIS Talent Management",
  "profil_cible": "Talents identifiés à potentiel leadership",
  "impact_attendu_technique": "Non quantifié dans les sources",
  "impact_attendu_metier": "Offre aux profils ambitieux une trajectoire vers le leadership — signal fort pour retenir ceux qui visent des responsabilités.",
  "delai_effet": "12 mois",
  "source_evidence": ["Suivi accord mixité diversité QVT 2024 vDef.pdf"],
  "extrait_source": "Des actions permettant d'accompagner de nouveaux talents tels que le programme YoungTalents ou RisingLeader continueront d'être déployés.",
  "a_completer": True,
  "note_extraction": "Programme cité sans détail propre dans les sources. Compléter avec documentation interne Talent Management."
},
{
  "action_id": "ACT_027",
  "titre": "Programme EVE leadership féminin",
  "description_technique": "Programme de leadership au féminin référencé dans le cycle de coaching du Projet Humain (Accord QVT 2024). Objectif : développer les viviers de talents féminins et accompagner les femmes à potentiel vers des responsabilités managériales. 51% de femmes dans les viviers Talents en 2023.",
  "description_metier": "Un programme de coaching leadership destiné aux femmes à potentiel — pour lever les freins à la prise de responsabilités et accroître la représentation féminine dans l'encadrement.",
  "gap_trigger": "Y < 3.40",
  "pattern_trigger": "Y < 3.40 ET λ >= moyenne groupe ET sous-représentation féminine dans le management (COMEX : 15,9% femmes en 2023)",
  "kpi_cible": "Y",
  "career_development": True,
  "type": "Coaching",
  "programme_parent": "Accord QVT",
  "duree": "Non précisé dans les sources",
  "organisme": "Programme EVE (externe) — CACEIS sponsor",
  "profil_cible": "Femmes à potentiel managérial identifiées",
  "impact_attendu_technique": "Indicateur QVT 2023 : 51% de femmes dans les viviers Talents. Objectif accord : développer les viviers féminins.",
  "impact_attendu_metier": "Aide les femmes à prendre confiance pour postuler à des rôles de direction — contribue à l'objectif de mixité managériale.",
  "delai_effet": "12 mois",
  "source_evidence": ["Suivi accord mixité diversité QVT 2024 vDef.pdf"],
  "extrait_source": "Leadership au féminin (Programme EVE). Développer les viviers de talents pour identifier les femmes à potentiel. Un leadership pour développer sans cesse le potentiel de chacun.",
  "a_completer": True,
  "note_extraction": "Programme EVE cité dans le cycle de coaching du Projet Humain sans détail sur la structure ou fréquence. Vérifier avec l'équipe Talent Management."
},
]

# ─────────────────────────────────────────────── Comptages
total = len(actions)
by_kpi = {}
for a in actions:
    k = a["kpi_cible"]
    by_kpi[k] = by_kpi.get(k, 0) + 1
n_career = sum(1 for a in actions if a["career_development"])
n_incomplete = sum(1 for a in actions if a["a_completer"])

output = {
  "metadata": {
    "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
    "version": "1.0",
    "source_pipeline": "extract_step1.py → build_action_library.py",
    "total_actions": total,
    "by_kpi": by_kpi,
    "career_development_count": n_career,
    "a_completer_count": n_incomplete,
    "kpi_mapping_v_hc": {
      "Y":  "Engagement + Performance EAE (fusion α + Y extraction)",
      "λ":  "Formation — taux réalisation plan formation (δ extraction)",
      "β":  "Qualité de vie au travail + QVCT bien-être (β extraction)",
      "ρ":  "Absentéisme + risque turnover (fusion λ + ρ extraction)",
      "P":  "Productivité — aucune action directe dans les sources disponibles"
    },
    "gap_notes": [
      {
        "kpi": "ρ",
        "message": "Actions limitées dans les sources disponibles. Les données sont principalement descriptives (taux d'absentéisme par motif, tableaux Bilans Sociaux). Les actions disponibles (ACT_021, ACT_022, ACT_023) sont des leviers indirects via β (QVCT) ou la rétention salariale. Aucun programme dédié à la réduction de l'absentéisme opérationnel n'a été identifié dans l'index ChromaDB."
      },
      {
        "kpi": "P",
        "message": "Aucune action directe sur la productivité (P) identifiée dans les sources indexées. P est un levier indirect des autres KPIs : Y (engagement → performance), λ (formation → compétences), β (QVCT → présentéisme efficace). Recommandation : compléter avec les sources Finance et Governance non exploitées sur ce KPI."
      }
    ],
    "sources_non_disponibles": [
      "We Care 2025 (cité dans les sources prioritaires — non présent dans l'index ChromaDB actuel)",
      "Enquête Managers irritants (non présente dans l'index ChromaDB actuel)"
    ]
  },
  "actions": actions
}

with open(OUT, "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"\n{'='*60}")
print(f"  ✅  action_library_raw.json généré")
print(f"      Fichier : {OUT}")
print(f"      Total actions      : {total}")
print(f"      Par KPI            : {by_kpi}")
print(f"      career_development : {n_career}")
print(f"      a_completer        : {n_incomplete}")
print(f"{'='*60}\n")
